CXXFLAGS =	-O2 -g -Wall -fmessage-length=0

OBJS =		eclipse-cpp-make-study-02.o

LIBS =

TARGET =	eclipse-cpp-make-study-02.exe

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
